feature1-2入力値エラー処理を追加しました。
hayatoogawa1/ex-emp-management-bugfix pull request #2
Opened 2024-11-22 08:12 UTC by hayatoogawa1

お疲れ様です。
小川駿斗です。

初級1-2　入力値エラー処理の追加が完了しました。
AdministratorControllerとInsertAdministratorFormでバリデーションを追加しました。

お手すきの際に、ご確認の程、よろしくお願いいたします。

2024-11-22 09:04 UTC, mariyamasan requested changes

2024-11-22 09:04 UTC, mariyamasan commented on src/main/resources/templates/administrator/insert.html
> -                        th:field="*{mailAddress}"
th:fieldは必要ですが、逆にvalueは必要ないかと思います。

下のpasswordも同じです。
これだと挙動がおかしいはずなので確認してみてください。

2024-11-22 09:04 UTC, mariyamasan commented on src/main/java/com/example/controller/AdministratorController.java
> +		redirectAttributes.addFlashAttribute("successMessage", "管理者登録を完了しました。");
画面に表示されていないのに使う必要はないかと思います。
今回はログイン画面に遷移すればいいので、ビュー側に何かを渡す必要もないと思われます！

2024-11-22 09:05 UTC, mariyamasan commented
@hayatoogawa1 難しいと思いますが、再度修正お願いします！

2024-11-25 04:52 UTC, hayatoogawa1 commented on src/main/java/com/example/controller/AdministratorController.java
> +		redirectAttributes.addFlashAttribute("successMessage", "管理者登録を完了しました。");
お疲れ様です。
入力値エラー処理の修正をしましたので
お手すきの際に、ご確認よろしくお願いいたします。

2024-11-25 04:56 UTC, mariyamasan commented
@hayatoogawa1 
OKです！！マージします！！

2024-11-25 04:56 UTC, merged

2024-11-25 05:06 UTC, hayatoogawa1 commented
ありがとうございます！！！